   - alias: 'Auto Renew SSL Cert'
     trigger:
       platform: numeric_state
       entity_id: sensor.ssl_cert_expiry
       below: 29
     action:
       - service: shell_command.renew_ssl

   - alias: Set Volume
     trigger:
       platform: state
       entity_id: input_select.volume_rxa2000
     action:
       - service: media_player.volume_set
         data_template:
           entity_id: media_player.rxa2000
           volume_level: '{{ 1+float(trigger.to_state.state)/100.0 }}'
           
   - alias: Set Volume on Startup
     trigger:
       platform: state
       entity_id: media_player.rxa2000
       from: 'off'
       to: 'on'
     action:
       - service: input_select.select_option
         data_template:
           entity_id: input_select.volume_rxa2000
           option: '{{ states.sensor.rxa2000_volume.state }}'
       
   - alias: Start Playing on Kodi
     trigger:
       platform: state
       entity_id: media_player.kodi
       to: 'playing'
     action:
        - service: scene.turn_on
          entity_id: scene.play_theatre

   - alias: Pause Playing on Kodi
     trigger:
       platform: state
       entity_id: media_player.kodi
       from: 'playing'
       to: 'paused'
     action:
        - service: scene.turn_on
          entity_id: scene.pause_theatre

   - alias: Stop Playing on Kodi
     trigger:
       platform: state
       entity_id: media_player.kodi
       from: 'playing'
       to: 'idle'
     action:
        - service: scene.turn_on
          entity_id: scene.pause_theatre
          